```{r}
# NCBI Women Led Hackathon 2019
  # Team Members: Hampton Leonard, Mary B Makarious, Ruth Chia, Sara Bandres-Ciga, Monica Diez-Fairen 
  # Last Updated: 09.05.2019

# Download the necessary packages if not already in environment 
if (!require(tidyverse)) install.packages('tidyverse')
if (!require(data.table)) install.packages('data.table')
if (!require(dplyr)) install.packages('dplyr')
if (!require(ggplot2)) install.packages('ggplot2')
if (!require(lme4)) install.packages('lme4')
if (!require(RNOmni)) install.packages('RNOmni')
if (!require(lmerTest)) install.packages('lmerTest')
```


```{r}
# Load the necessary packages 
library(tidyverse)
library(data.table)
library(dplyr)
library(ggplot2)
library(RNOmni)
library(lme4)
library(lmerTest)

# Set working directory 
setwd("/Users/makariousmb/Desktop/Hackathon_Code/Hackathon")

# Read in the dataset
tbl <- read.table("ppmi_hackathon_data.txt", header = T)
```


```{r}
# Scale everything to be able to be fed into LMM 
### to do - automatically scale all provided covariates

tbl_scaled <- tbl

tbl_scaled$TSTART <- scale(tbl_scaled$TSTART, center = F)
tbl_scaled$YEARSEDUC <- scale(tbl_scaled$YEARSEDUC, center = F)
tbl_scaled$AAO <- scale(tbl_scaled$AAO, center = F)


# Put scaled data into model
### to do - automatically put in correct phenotype of choice and covariates
### to do - stepwise selection of covariates for best model
  ## TODO: Add LDOPA and AGONIST data as covariates 
updrs3_slope <- lmer(UPDRS3_scaled ~ FEMALE + YEARSEDUC + AAO + DOPA + AGONIST + (TSTART|ID), tbl_scaled, REML = T)

# Get the summary
summary(updrs3_slope)

# Get patient-specific slopes 
raneffect_updrs3 <- as.data.frame(ranef(updrs3_slope)$ID)
raneffect_updrs3$`(Intercept)` <- NULL
raneffect_updrs3$ID <- rownames(raneffect_updrs3)
  # plot(density(raneffect_updrs3$TSTART))

### Should we normalize?
  # Attempt with and without normalization and plot AUC plots
  # See which is more biologically relevant?

### to do - output metrics of model fit, maybe AUC plots etc
```

```{r}

# ggplot-style Density Plot 
slope_density_plot <- ggplot(raneffect_updrs3, aes(x=TSTART)) +
  geom_density(color="darkblue", fill="lightblue", alpha=0.4) + 
  theme_bw() +
  ggtitle("Density of Patient Slopes") + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  labs(x = "Slopes of Patients",
       y = "Density") 

# Save the density plot 
ggsave("Desnity_PatientSlopes.png", slope_density_plot, width = 3, height = 2, units = "in")

# View the plot 
slope_density_plot

# output patient slopes
## to do - make output go to location specified by user

write.table(raneffect_updrs3, "patient_slopes.txt",  sep = "\t", append = F, row.names = F, quote = F, col.names = T)
```

```{r}
# Experimental
# Backwards elimination of random and fixed effects of the model 

# Backward elimination using terms with default alpha-levels:
  # Keep random effects
  # Note: User should not put in more than one random effect 
(step_res <- step(updrs3_slope, reduce.random = FALSE))
back_elim_updrs3_model <- get_model(step_res)
anova(back_elim_updrs3_model)

# Print out summary stats
summary(back_elim_updrs3_model)

```

```{r}
# Get patient-specific slopes following the backwards elimination step function 
raneffect_updrs3_backelim <- as.data.frame(ranef(back_elim_updrs3_model)$ID)
raneffect_updrs3_backelim$`(Intercept)` <- NULL
raneffect_updrs3_backelim$ID <- rownames(raneffect_updrs3_backelim)

# ggplot-style Density Plot after the step function 
slope_density_plot_2 <- ggplot(raneffect_updrs3_backelim, aes(x=TSTART)) +
  geom_density(color="darkgreen", fill="lightgreen", alpha=0.4) + 
  theme_bw() +
  ggtitle("Density of Patient Slopes following Backwards Elimination Stepwise Function") + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  labs(x = "Slopes of Patients",
       y = "Density") 

# Save the density plot 
ggsave("Desnity_PatientSlopes_Step.png", slope_density_plot_2, width = 3, height = 2, units = "in")

# View the plot
slope_density_plot_2
  # With our PPMI data, these plots look the same (meaning the model was most useful with all the information)

```

```{r}
##TODO: 
  # Output summary statistics 
  # Interpretation section on the README
    # What each plot means 
  # Plots to show the variance 
  # Output error message for when the model coverges
    # Output top 3 reasons why the model would converge 

```



